account.msg =Welcome to the bank account development application
account.build-version=1

account.mailDetails.hostName=development-account@khem.com
account.mailDetails.port=9000
account.mailDetails.from=development-account@khem.com
account.mailDetails.subject=Your account details from khem bank development environment

account.activeBranches[0]=Siem Reap
account.activeBranches[1]=Takeo
account.activeBranches[2]=Kep