account.msg =Welcome to the bank account production application
account.build-version=3

account.mailDetails.hostName=production-account@khem.com
account.mailDetails.port=9000
account.mailDetails.from=production-account@khem.com
account.mailDetails.subject=Your account details from bank production environment

account.activeBranches[0]=Kondal
account.activeBranches[1]=kompot
account.activeBranches[2]=Svey Reng