spring:
  
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_service_db?currentSchema=card_schema
    driver-class-name: org.postgresql.Driver
    username: card_user
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
# Optional: Custom banner location
banner:
  location: classpath:/banner/banner.txt

# application info
card:
  message: Card Development Environment
  build-version: 0.0.1
  
  mail-detail:
    hostname: development-card@khem.com
    port: 1001
    from-address: development-card@khem.com
    subject: Card Development Environment

  active-branch:
    - Phnom Penh
    - Siem Reap
    - Battombong
